import type { TimelineDocument } from "../../../../../packages/timeline-schema/src/types";

export const sampleTimeline: TimelineDocument = {
  schemaVersion: "1.0",
  id: "local-dev-timeline",
  title: "Incident Timeline",
  description: "Initial local development timeline",
  timezone: "America/New_York",
  lanes: [
    {
      id: "security-ops",
      name: "Security Operations"
    },
    {
      id: "it-operations",
      name: "IT Operations"
    },
    {
      id: "legal-compliance",
      name: "Legal / Compliance"
    }
  ],
  events: [
    {
      id: "evt-001",
      order: 0,
      title: "Alert received",
      description: "Initial alert generated by monitoring system.",
      start: "2026-06-18T08:00:00-04:00",
      end: null,
      laneId: "security-ops",

      category: "Detection",
      eventType: "Alert",
      status: "Initial Access",
      severity: "High",

      color: "#2563eb",
      icon: "Alert",
      displayStyle: "Solid",

      tags: ["security", "alert"],
      source: "Manual entry",
      evidenceUrl: "",
      confidence: "High",
      actor: "Security Operations",
      location: "SOC",

      createdAt: "2026-06-18T08:00:00-04:00",
      updatedAt: "2026-06-18T08:00:00-04:00"
    }
  ],
  createdAt: "2026-06-18T08:00:00-04:00",
  updatedAt: "2026-06-18T08:00:00-04:00"
};